version: "3"
services:
  app:
    build: .
    container_name: genshin
    command: /app/commands/run.sh
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8070:8000
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: genshin-db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=genshin
      - MYSQL_DATABASE=genshin_dev
      - MYSQL_USER=genshin
      - MYSQL_PASSWORD=genshinpass

volumes:
  mysql-data:
